# Generated by Django 6.0.3 on 2026-09-02 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(default='Operations', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.CharField(default='Intern', max_length=50)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin / Operations Manager'), ('employee', 'Employee / Team Member')], default='employee', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('emp_code', models.CharField(blank=True, default='', max_length=50)),
                ('designation', models.CharField(blank=True, default='', max_length=150)),
                ('department', models.CharField(blank=True, default='Operations', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', max_length=20)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255)),
                ('skills', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ops_core.operationalrole')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ops_core.operationuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Todo', 'To Do'), ('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Completed', 'Completed')], default='Todo', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(default=0.0)),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('attachment_url', models.CharField(blank=True, default='', max_length=255)),
                ('submission_notes', models.TextField(blank=True, default='')),
                ('submission_link', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='ops_core.operationuser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='ops_core.operationuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_spent', models.FloatField(default=0.0)),
                ('work_summary', models.TextField()),
                ('submission_link', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='ops_core.operationuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ops_core.worktask')),
            ],
        ),
    ]
