# Generated by Django 6.0.3 on 2026-09-03 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Checked In', 'Currently Working'), ('Completed', 'Shift Completed'), ('Half Day', 'Half Day'), ('Late', 'Late Check-In')], default='Checked In', max_length=30)),
                ('work_mode', models.CharField(default='Office', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='ops_core.operationuser')),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
