# Generated by Django 6.0.3 on 2026-09-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0002_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationuser',
            name='assigned_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='assigned_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='assigned_roles',
            field=models.ManyToManyField(blank=True, related_name='members_multi', to='ops_core.operationalrole'),
        ),
    ]
