# Generated by Django 6.0.3 on 2026-09-07 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0003_operationuser_assigned_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('page_key', models.CharField(max_length=150, unique=True, verbose_name='Page Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='operationuser',
            options={'ordering': ['name', 'email'], 'verbose_name': 'OP user', 'verbose_name_plural': 'OP users'},
        ),
        migrations.AddField(
            model_name='operationuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='department',
            field=models.CharField(blank=True, default='Operations', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='emp_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Operations Manager'), ('employee', 'Employee / Team Member')], default='employee', max_length=20, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('otp_code', models.CharField(max_length=10, verbose_name='OTP Code')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_otps', to='ops_core.operationuser', verbose_name='OP User')),
            ],
            options={
                'verbose_name': 'Login otp',
                'verbose_name_plural': 'Login otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255, unique=True, verbose_name='Session Token')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_sessions', to='ops_core.operationuser', verbose_name='OP User')),
            ],
            options={
                'verbose_name': 'OP session',
                'verbose_name_plural': 'OP sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPUserDepartmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='ops_core.department', verbose_name='Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_accesses', to='ops_core.operationuser', verbose_name='OP User')),
            ],
            options={
                'verbose_name': 'OP User Department Access',
                'verbose_name_plural': 'OP User Department Accesses',
                'ordering': ['user', 'department'],
                'unique_together': {('user', 'department')},
            },
        ),
    ]
