# Generated by Django 6.0.3 on 2026-09-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0004_department_alter_operationuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationuser',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
