# Generated by Django 6.0.3 on 2026-10-01 05:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0005_alter_operationuser_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrackerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_hours', models.IntegerField(default=24)),
                ('task_types_json', models.TextField(default='["Major", "Minor", "Research", "Documentation", "Meeting", "Support"]')),
                ('custom_fields_json', models.TextField(default='[]')),
                ('auto_lock_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Tracker Config',
                'verbose_name_plural': 'Daily Tracker Configs',
            },
        ),
        migrations.AddField(
            model_name='operationuser',
            name='emp_type',
            field=models.CharField(default='Normal', max_length=50, verbose_name='Employee Type'),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Is Manager'),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='Is Superadmin'),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='managed_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Managed Department'),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='managed_departments',
            field=models.JSONField(blank=True, default=list, verbose_name='Managed Departments List'),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='ops_core.operationuser'),
        ),
        migrations.CreateModel(
            name='DailyAssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('task_type', models.CharField(default='Major', max_length=50)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_assigned_tasks_created', to='ops_core.operationuser')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_assigned_tasks_received', to='ops_core.operationuser')),
            ],
            options={
                'verbose_name': 'Daily Assigned Task',
                'verbose_name_plural': 'Daily Assigned Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrackerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('day_number', models.IntegerField(default=1)),
                ('day_status', models.CharField(default='Working Day', max_length=30)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('manager_rating', models.IntegerField(default=0)),
                ('manager_remarks', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_trackers', to='ops_core.operationuser')),
            ],
            options={
                'verbose_name': 'Daily Tracker Day',
                'verbose_name_plural': 'Daily Tracker Days',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTrackerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('performed_by_name', models.CharField(max_length=150)),
                ('performed_by_role', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops_core.operationuser')),
                ('tracker_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ops_core.dailytrackerday')),
            ],
            options={
                'verbose_name': 'Daily Tracker Audit Log',
                'verbose_name_plural': 'Daily Tracker Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('task_type', models.CharField(default='Major', max_length=50)),
                ('hours_worked', models.FloatField(default=0.0)),
                ('is_achievement', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('custom_data', models.TextField(blank=True, default='{}', null=True)),
                ('assigned_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_log_rows', to='ops_core.dailyassignedtask')),
                ('tracker_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ops_core.dailytrackerday')),
            ],
            options={
                'verbose_name': 'Daily Task Row',
                'verbose_name_plural': 'Daily Task Rows',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrackerUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('tracker_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='ops_core.dailytrackerday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_unlock_requests', to='ops_core.operationuser')),
            ],
            options={
                'verbose_name': 'Daily Tracker Unlock Request',
                'verbose_name_plural': 'Daily Tracker Unlock Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers_appointed', to='ops_core.operationuser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='ops_core.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_managements', to='ops_core.operationuser')),
            ],
            options={
                'verbose_name': 'Department Manager Assignment',
                'verbose_name_plural': 'Department Manager Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
