# Generated by Django 6.0.3 on 2026-10-01 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0006_dailytrackerconfig_operationuser_emp_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, verbose_name='Stock Symbol / Ticker')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('sector', models.CharField(blank=True, default='Equities', max_length=100)),
                ('client_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Client / Portfolio Name')),
                ('recommendation_type', models.CharField(choices=[('Buy', 'Buy'), ('Strong Buy', 'Strong Buy'), ('Accumulate', 'Accumulate'), ('Hold', 'Hold'), ('Sell', 'Sell')], default='Buy', max_length=30)),
                ('recommendation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Recommended Date')),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Recommended Buying Price (₹)')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target Price (₹)')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Stop Loss (₹)')),
                ('time_horizon', models.CharField(default='3 Months', max_length=50, verbose_name='Time Horizon')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Last Tracked Market Price')),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Target Hit', 'Target Hit'), ('Stop Loss Hit', 'Stop Loss Hit'), ('Closed', 'Closed')], default='Active', max_length=30)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Investment Rationale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_recommendations', to='ops_core.operationuser')),
            ],
            options={
                'verbose_name': 'Stock Recommendation',
                'verbose_name_plural': 'Stock Recommendations',
                'ordering': ['-recommendation_date', '-created_at'],
            },
        ),
    ]
