# Generated by Django 6.0.3 on 2026-10-05 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0007_stockrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Checked In', 'Currently Working'), ('Completed', 'Shift Completed'), ('Half Day', 'Half Day'), ('Late', 'Late Check-In')], db_index=True, default='Checked In', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyassignedtask',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyassignedtask',
            name='priority',
            field=models.CharField(db_index=True, default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyassignedtask',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailytrackerday',
            name='status',
            field=models.CharField(db_index=True, default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='departmentmanagerassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='department',
            field=models.CharField(blank=True, db_index=True, default='Operations', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Operations Manager'), ('employee', 'Employee / Team Member')], db_index=True, default='employee', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], db_index=True, default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], db_index=True, default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.CharField(choices=[('Todo', 'To Do'), ('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Completed', 'Completed')], db_index=True, default='Todo', max_length=20),
        ),
    ]
